# NumPy

To work with NumPy you should import it

In [1]:
import numpy as np

You can create NumPy array from python list

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

Or without temporary variable

In [5]:
arr = np.array([1, 2, 3])

In [6]:
arr

array([1, 2, 3])

## arange
Return evenly spaced values within a given interval.

In [7]:
np.arange(3)

array([0, 1, 2])

In [8]:
np.arange(3.0)

array([0., 1., 2.])

In [9]:
np.arange(3,7)

array([3, 4, 5, 6])

In [10]:
np.arange(3,7,2)

array([3, 5])

## zeros
Return a new array of given shape and type, filled with zeros.

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,), dtype=np.int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## ones
Return a new array of given shape and type, filled with ones.

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((5,), dtype=np.int)

array([1, 1, 1, 1, 1])

In [17]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## linspace
Return evenly spaced numbers over a specified interval.

In [19]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [20]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [21]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

## random.randint
Return random integers from low (inclusive) to high (exclusive).

In [22]:
np.random.randint(2, size=10)

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1])

In [23]:
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.random.randint(5, size=(2, 4))

array([[0, 1, 4, 3],
       [2, 0, 2, 3]])

## random.normal
Draw random samples from a normal (Gaussian) distribution.

In [25]:
np.random.normal(0, 0.1, 10)

array([-0.08125015,  0.1326402 ,  0.05018767,  0.03450276, -0.09245761,
        0.01135142, -0.03083326,  0.02629918, -0.10943387,  0.03329231])

## random.seed
Seed the generator.

In [26]:
np.random.seed(101)
np.random.randint(2, size=5)

array([1, 1, 1, 0, 1])

The same

In [27]:
np.random.seed(101)
np.random.randint(2, size=5)

array([1, 1, 1, 0, 1])

## max

In [28]:
arr = np.array(np.random.randint(10, size=10))

In [29]:
arr

array([7, 9, 8, 4, 8, 5, 0, 5, 8, 1])

In [30]:
arr.max()

9

## min

In [31]:
arr.min()

0

## mean

In [32]:
arr.mean()

5.5

## argmax

In [33]:
arr.argmax()

1

## reshape
Gives a new shape to an array without changing its data.

In [34]:
arr.reshape((2, 5))

array([[7, 9, 8, 4, 8],
       [5, 0, 5, 8, 1]])

In [35]:
arr.reshape((1, 10))

array([[7, 9, 8, 4, 8, 5, 0, 5, 8, 1]])

In [36]:
arr.reshape((10, 1))

array([[7],
       [9],
       [8],
       [4],
       [8],
       [5],
       [0],
       [5],
       [8],
       [1]])

In [37]:
arr.reshape((5, 2))

array([[7, 9],
       [8, 4],
       [8, 5],
       [0, 5],
       [8, 1]])

## Access to elements

In [38]:
arr = np.random.randint(10, size=100).reshape((10, 10))
arr

array([[3, 8, 3, 3, 2, 8, 9, 3, 7, 0],
       [9, 7, 9, 8, 4, 3, 3, 7, 4, 8],
       [7, 6, 9, 4, 2, 7, 7, 7, 0, 4],
       [1, 8, 3, 1, 8, 4, 3, 2, 3, 3],
       [7, 4, 8, 6, 3, 7, 6, 5, 6, 9],
       [2, 2, 1, 3, 3, 3, 4, 5, 9, 5],
       [8, 3, 6, 8, 7, 5, 7, 5, 4, 4],
       [7, 3, 2, 3, 2, 9, 3, 5, 6, 6],
       [5, 5, 1, 7, 4, 7, 4, 5, 1, 6],
       [9, 2, 6, 3, 8, 1, 7, 4, 1, 8]])

In [39]:
arr[5,5]

3

In [40]:
arr[0,0]

3

In [41]:
arr[9,9]

8

In [42]:
arr[:,0]

array([3, 9, 7, 1, 7, 2, 8, 7, 5, 9])

In [43]:
arr[0,:]

array([3, 8, 3, 3, 2, 8, 9, 3, 7, 0])

In [44]:
arr[:3,:3]

array([[3, 8, 3],
       [9, 7, 9],
       [7, 6, 9]])

In [45]:
arr > 5

array([[False,  True, False, False, False,  True,  True, False,  True,
        False],
       [ True,  True,  True,  True, False, False, False,  True, False,
         True],
       [ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [False,  True, False, False,  True, False, False, False, False,
        False],
       [ True, False,  True,  True, False,  True,  True, False,  True,
         True],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [ True, False,  True,  True,  True, False,  True, False, False,
        False],
       [ True, False, False, False, False,  True, False, False,  True,
         True],
       [False, False, False,  True, False,  True, False, False, False,
         True],
       [ True, False,  True, False,  True, False,  True, False, False,
         True]])

In [46]:
arr[arr > 5]

array([8, 8, 9, 7, 9, 7, 9, 8, 7, 8, 7, 6, 9, 7, 7, 7, 8, 8, 7, 8, 6, 7,
       6, 6, 9, 9, 8, 6, 8, 7, 7, 7, 9, 6, 6, 7, 7, 6, 9, 6, 8, 7, 8])